---
title: ""
output: pdf_document
---

```{r setup, include=FALSE, cache = T}
knitr::opts_chunk$set(fig.width=12, fig.height=8, fig.path='Figs/',
                      echo=TRUE, warning=FALSE, message=FALSE)
```



```{r setup2, include=F, cache = T}


library(ggplot2)
library(cowplot)
library(BayesFactor)
library(lme4)
library(lmerTest)
theme = theme(panel.grid.major = element_blank(), 
              panel.grid.minor = element_blank(), 
              panel.background = element_blank(), 
              axis.line = element_line(colour = "black"), 
              legend.key = element_rect(fill = "white"),
              text = element_text(size = 15))
dodge = position_dodge(width = 0.8)


path = 'S:/expt/eeg/eeg01/analyses/subject_data_files'
data_files = list.files(path)[grep('csv', list.files(path))]
parent_data = data.frame()
for(x in data_files){
  t_file = paste(c(path,'/', x), collapse = '')
  temp = read.csv(t_file)
  parent_data = rbind(parent_data, temp)
  
}
parent_data = parent_data[ , -c(10)]
datacom = parent_data
zscores = scale(datacom$rt)
summary(abs(zscores) < 3)
dataACC = subset(datacom, abs(zscores) < 3)
#now only keep correctly answered old1, old2, and old3 words
dataBuild = subset(dataACC, event_type == 2 | event_type == 3 | event_type == 4)
dataBuild$repetition = 'place_hold'
for(x in 1:nrow(dataBuild)){
  if(dataBuild$event_type[x]==2){
    dataBuild$repetition[x] = 'old1'
  } else if(dataBuild$event_type[x]==3){
    dataBuild$repetition[x] = 'old2'
  } else if(dataBuild$event_type[x]==4){
    dataBuild$repetition[x] = 'old3'
  }
}
dataBuild$repetition = factor(dataBuild$repetition)
dataBuild$lag_log = log(dataBuild$lag, base=2)
data_all = dataBuild
o1d = subset(data_all, repetition == 'old1')
o2d = subset(data_all, repetition == 'old2')
o3d = subset(data_all, repetition == 'old3')
data_all2 = data_all



```

variance by repetition
```{r vares, cache=T}
#variance by repetition
with(data_all2, tapply(rt,list(repetition),sd,na.rm=T))
```

### accuracy and RT 
```{r accRT, cache=T}
data2 = subset(dataACC, !(event_type %in% c(0,5,10)))
data2$condition = NA
for(x in 1:nrow(data2)){
  if(data2$event_type[x] == 1 | data2$event_type[x] == 6){
    data2$condition[x] = 'New'
  } else if(data2$event_type[x] == 2 | data2$event_type[x] == 7){
    data2$condition[x] = 'Old1'
  } else if(data2$event_type[x] == 3 | data2$event_type[x] == 8){
    data2$condition[x] = 'Old2'
  } else {
    data2$condition[x] = 'Old3'
  }
}
table(data2$condition)
data3=data2
data3$acc = NA
for(x in 1:nrow(data3)){
  if(data3$event_type[x] == 1 | data3$event_type[x] == 2 | 
     data3$event_type[x] == 3 | data3$event_type[x] == 4) {
    data3$acc[x] = 1
  } else {
    data3$acc[x] = 0
  }
}



tot_acc_dat_w = data.frame()
tot_acc_dat_p = data.frame()
for(x in unique(data3$subject)){
  tmpdat = subset(data3, subject == x)
  tmpdat_w = subset(tmpdat, word_picture == 1)
  tmpdat_p = subset(tmpdat, word_picture == 2)
  
  tmptab = with(tmpdat_w, tapply(acc, list(condition),mean,na.rm=T))
  tmpdat2 = data.frame(cbind(names(tmptab),unname(tmptab)))
  names(tmpdat2) = c('repetition','acc')
  tmpdat2$acc = as.numeric(as.character(tmpdat2$acc))
  tmpdat2$subject = x
  tot_acc_dat_w = rbind(tot_acc_dat_w, tmpdat2)
  
  tmptab2 = with(tmpdat_p, tapply(acc, list(condition),mean,na.rm=T))
  tmpdat22 = data.frame(cbind(names(tmptab2),unname(tmptab2)))
  names(tmpdat22) = c('repetition','acc')
  tmpdat22$acc = as.numeric(as.character(tmpdat22$acc))
  tmpdat22$subject = x
  tot_acc_dat_p = rbind(tot_acc_dat_p, tmpdat22)
}

tot_acc_dat_p$wordpic = 'Picture'
tot_acc_dat_w$wordpic = 'Word'
tmpaccdat = data.frame(rbind(tot_acc_dat_p, tot_acc_dat_w))


tot_rt_dat_w = data.frame()
tot_rt_dat_p = data.frame()
for(x in unique(data3$subject)){
  tmpdat = subset(data3, subject == x)
  tmpdat_w = subset(tmpdat, word_picture == 1)
  tmpdat_p = subset(tmpdat, word_picture == 2)
  
  tmptab = with(tmpdat_w, tapply(rt, list(condition),mean,na.rm=T))
  tmpdat2 = data.frame(cbind(names(tmptab),unname(tmptab)))
  names(tmpdat2) = c('repetition','rt')
  tmpdat2$rt = as.numeric(as.character(tmpdat2$rt))
  tmpdat2$subject = x
  tot_rt_dat_w = rbind(tot_rt_dat_w, tmpdat2)
  
  tmptab2 = with(tmpdat_p, tapply(rt, list(condition),mean,na.rm=T))
  tmpdat22 = data.frame(cbind(names(tmptab2),unname(tmptab2)))
  names(tmpdat22) = c('repetition','rt')
  tmpdat22$rt = as.numeric(as.character(tmpdat22$rt))
  tmpdat22$subject = x
  tot_rt_dat_p = rbind(tot_rt_dat_p, tmpdat22)
}

tot_rt_dat_p$wordpic = 'Picture'
tot_rt_dat_w$wordpic = 'Word'
tmprtdat = data.frame(rbind(tot_rt_dat_p,tot_rt_dat_w))


## plot accuracy and RTs
windowsFonts(Times=windowsFont("Arial"))
a3 = ggplot(tmpaccdat, aes(repetition,y=acc, fill = wordpic)) +
  geom_boxplot(width=.3, position = dodge, outlier.shape = NA,alpha=0.65)+
  geom_point(color="gray10", size=1.1, position = dodge,alpha=.9) +
  theme +theme(text=element_text(family="Times",size=16))+
  xlab("") + ylab("Accuracy") + 
  scale_x_discrete(labels = c('New','Old 1','Old 2','Old3')) + 
  scale_fill_manual(values=c('blue','red'), name = '') +
  scale_color_manual(values=c('blue','red'))+
  coord_cartesian(ylim=c(.5,1))

windowsFonts(Times=windowsFont("Arial"))
r3 = ggplot(tmprtdat, aes(repetition,y=rt, fill = wordpic)) +
  geom_boxplot(width=.3, position = dodge, outlier.shape = NA, alpha = 0.65)+
  geom_point(color="gray10", size=1.1, position = dodge,alpha=.9) +
  theme +theme(text=element_text(family="Times",size=16))+
  xlab("Repetition") + ylab("Response Time") + 
  scale_x_discrete(labels = c('New','Old 1','Old 2','Old3')) + 
  scale_fill_manual(values=c('blue','red'),name = '') +
  scale_color_manual(values=c('blue','red'))+
  coord_cartesian(ylim=c(500,1000))




p2 = plot_grid(a3,r3,ncol = 1, labels = c('A ','B '), label_size = 15)
save_plot('C:/Users/jscof/OneDrive - University of Missouri/eeg01_analyses_final/fig1_beh_plotnest.png',
          plot = p2, ncol = 1, nrow=2, base_height = 4, base_aspect_ratio = 1.6)


```

### Acc pairwise comparisons
```{r accpairwise, cache=T}
#accuracy pairwise comparisons
td1 = subset(data3, (condition == 'New') | (condition == 'Old1'))
td1$condition = factor(td1$condition)
td2 = subset(data3, (condition == 'New') | (condition == 'Old2'))
td2$condition = factor(td2$condition)
td3 = subset(data3, (condition == 'New') | (condition == 'Old3'))
td3$condition = factor(td3$condition)
td4 = subset(data3, (condition == 'Old1') | (condition == 'Old2'))
td4$condition = factor(td4$condition)
td5 = subset(data3, (condition == 'Old1') | (condition == 'Old3'))
td5$condition = factor(td5$condition)
td6 = subset(data3, (condition == 'Old2') | (condition == 'Old3'))
td6$condition = factor(td6$condition)

generalTestBF(acc ~ condition, data = td1, whichRandom = 'subject')
generalTestBF(acc ~ condition, data = td4, whichRandom = 'subject')
generalTestBF(acc ~ condition, data = td5, whichRandom = 'subject')


generalTestBF(acc ~ condition, data = td2, whichRandom = 'subject')
generalTestBF(acc ~ condition, data = td3, whichRandom = 'subject')
generalTestBF(acc ~ condition, data = td6, whichRandom = 'subject')

#for comparison (frequentist)
summary(lmer(acc ~ condition + (1|subject), data = td1))
summary(lmer(acc ~ condition + (1|subject), data = td4))
summary(lmer(acc ~ condition + (1|subject), data = td5))

summary(lmer(acc ~ condition + (1|subject), data = td2))
summary(lmer(acc ~ condition + (1|subject), data = td3))
summary(lmer(acc ~ condition + (1|subject), data = td6))


```


###plot RT slopes
```{r plotrtslope, cache=T}
subs = as.numeric(names(table(data_all2$subject)))
ind_dat = data.frame(matrix(ncol = 7, nrow = 15))
colnames(ind_dat) = c('subject','o1I','o1S','o2I','o2S','o3I','o3S')

round=1
for(x in subs){
  tmpdat = subset(data_all2, subject == x)
  tmpo1 = subset(tmpdat, repetition == 'old1')
  tmpo2 = subset(tmpdat, repetition == 'old2')
  tmpo3 = subset(tmpdat, repetition == 'old3')
  ind_dat$subject[round] = x
  ind_dat$o1I[round] = unname(lm(rt ~ lag_log, data = tmpo1)$`coefficients`[1])
  ind_dat$o1S[round] = unname(lm(rt ~ lag_log, data = tmpo1)$`coefficients`[2])
  ind_dat$o2I[round] = unname(lm(rt ~ lag_log, data = tmpo2)$`coefficients`[1])
  ind_dat$o2S[round] = unname(lm(rt ~ lag_log, data = tmpo2)$`coefficients`[2])  
  ind_dat$o3I[round] = unname(lm(rt ~ lag_log, data = tmpo3)$`coefficients`[1])
  ind_dat$o3S[round] = unname(lm(rt ~ lag_log, data = tmpo3)$`coefficients`[2])
  round = round + 1
}


o1dat = subset(data_all2, repetition == 'old1')
o2dat = subset(data_all2, repetition == 'old2')
o3dat = subset(data_all2, repetition == 'old3')
o1 = unname(lm(rt ~ lag_log, data = o1dat)$`coefficients`)
o2 = unname(lm(rt ~ lag_log, data = o2dat)$`coefficients`)
o3 = unname(lm(rt ~ lag_log, data = o3dat)$`coefficients`)

theme = theme(panel.grid.major = element_blank(), 
              panel.grid.minor = element_blank(), 
              panel.background = element_blank(), 
              axis.line = element_line(colour = "black"), 
              legend.key = element_rect(fill = "white"),
              text = element_text(size = 23, family='sans'),
              legend.position='none',
              plot.title = element_text(size = 23, face = 'plain'),
              axis.text.x= element_text(size=18),
              axis.text.y= element_text(size=18),
              axis.title=element_text(size=23),
              plot.margin=unit(c(0,0,0,0),"cm"))

ind_dat_1 = ind_dat[,c(1:3)]
windowsFonts(Times=windowsFont("Arial"))
o1_plot = ggplot(o1dat,aes(y = rt, x = lag_log)) +
  geom_abline(aes(intercept=o1I, slope=o1S),data=ind_dat_1, color = 'red',alpha = 0.2)+
  geom_smooth(method = "lm", color = 'red',alpha=0.5) + xlab("Lag") + ylab("Response Time") +
  coord_cartesian(ylim=c(550,950),xlim=c(2,5)) + 
  theme 
ind_dat_2 = ind_dat[,c(1,4:5)]
windowsFonts(Times=windowsFont("Arial"))
o2_plot = ggplot(o2dat,aes(y = rt, x = lag_log)) +
  geom_abline(aes(intercept=o2I, slope=o2S),data=ind_dat_2, color = 'darkgreen',alpha = 0.2)+
  geom_smooth(method = "lm", color = 'darkgreen',alpha=0.5) + labs(x='Lag',y=NULL) +
  coord_cartesian(ylim=c(550,950),xlim=c(2,5)) + 
  theme
ind_dat_3 = ind_dat[,c(1,6:7)]
windowsFonts(Times=windowsFont("Arial"))
o3_plot = ggplot(o3dat,aes(y = rt, x = lag_log)) +
  geom_abline(aes(intercept=o3I, slope=o3S),data=ind_dat_3, color = 'blue',alpha = 0.2)+
  geom_smooth(method = "lm", color = 'blue',alpha=0.5) + labs(x='Lag',y=NULL) +
  coord_cartesian(ylim=c(550,950)) + 
  theme


pgrid2 = plot_grid(o1_plot,o2_plot,o3_plot, ncol=3,nrow=1, scale=0.9,
                    labels = c('A','B','C'), label_size = 19,
                    label_fontfamily = 'sans')
#save_plot('C:/Users/jscof/OneDrive - University of Missouri/eeg01_analyses_final/fig2_RT_lag_plots.png',
#          pgrid2, ncol=3,nrow=1, base_height = 6, base_aspect_ratio = 1.1,
#          type = 'cairo')

```
