---
title: "ERP 9electrode analysis"
output: pdf_document
---

```{r setup, include=FALSE, cache = T}
knitr::opts_chunk$set(fig.width=12, fig.height=8, fig.path='Figs/',
                      echo=TRUE, warning=FALSE, message=FALSE)
```

## set up
```{r setup2, include=T, results='hide', echo=F, cache=T}
library(readxl)
library(brms)
dat <- read_excel("S:/expt/eeg/eeg01/analyses/erp_amplitude_500800ms_by9electrodes.csv", 
                                                   col_names = FALSE)
colnames(dat) = c('subject','trial','wordpic','repetition','ACP','LMR','amplitude')

dat$repetition = factor(dat$repetition)
dat$ACP = factor(dat$ACP)
dat$LMR = factor(dat$LMR)

nonew = subset(dat, repetition != 1)
nonew$repetition = factor(nonew$repetition)
```

## estimate models
```{r estimate, echo=T, results = 'hide', cache=T}
mod_pri = c(prior(normal(0,1), class=b),
            prior(cauchy(0,2), class=sigma))

mod_intercept = brm(amplitude ~ 1 + (1 | subject), data = dat, save_all_pars = T)
mod_rep = brm(amplitude ~ repetition + (1 | subject), 
                      data = dat, prior = mod_pri, save_all_pars = T)
mod_rep_ACP = brm(amplitude ~ repetition + ACP + (1 | subject),
                  data = dat, prior = mod_pri, save_all_pars = T)
mod_rep_LMR = brm(amplitude ~ repetition + LMR + (1 | subject),
                  data = dat, prior = mod_pri, save_all_pars = T)
mod_rep_ACP_LMR = brm(amplitude ~ repetition + ACP + LMR + (1 | subject),
                      data = dat, prior = mod_pri, save_all_pars = T)
mod_interact = brm(amplitude ~ repetition*ACP*LMR + (1 | subject),
                   data = dat, prior = mod_pri, save_all_pars = T)
```

```{r estimatenonew, echo=T, results = 'hide', cache=T}
mod_pri = c(prior(normal(0,1), class=b),
            prior(cauchy(0,2), class=sigma))

mod_intercept_nonew = brm(amplitude ~ 1 + (1 | subject), data = nonew, save_all_pars = T)
mod_rep_nonew = brm(amplitude ~ repetition + (1 | subject), 
                      data = nonew, prior = mod_pri, save_all_pars = T)
```


## Calculate Bayes Factors
```{r calcBF, echo=T, results = 'hide', cache=T}
#rep
bf1 = bayes_factor(mod_rep, mod_intercept)$bf
#ACP
bf2 = bayes_factor(mod_rep_ACP, mod_rep)$bf
#LMR
bf3 = bayes_factor(mod_rep_LMR, mod_rep)$bf
#ACP2
bf4 = bayes_factor(mod_rep_ACP_LMR, mod_rep_LMR)$bf
#LMR2
bf5 = bayes_factor(mod_rep_ACP_LMR, mod_rep_ACP)$bf
#main eff
bf6 = bayes_factor(mod_rep_ACP_LMR, mod_rep)$bf
#interact
bf7 = bayes_factor(mod_interact, mod_rep_ACP_LMR)$bf
```

```{r calcBFnonew, echo=T, results = 'hide', cache=T}
#rep no new
bf1_nonew = bayes_factor(mod_rep_nonew, mod_intercept_nonew)$bf

```

## list Bayes Factors
```{r bf, include = T, cache=T}
#rep
bf1
#ACP
bf2
#LMR
bf3
#ACP2
bf4
#LMR2
bf5
#main eff
bf6
#interact
bf7

waic(mod_intercept, mod_rep, mod_rep_ACP,
     mod_rep_LMR, mod_rep_ACP_LMR, mod_interact)

```

```{r bfnonew, include = T, cache=T}
#rep
bf1_nonew

waic(mod_intercept_nonew, mod_rep_nonew)

```

## Interaction effects for each repetition vs new

```{r subdata, include=T, cache=T}
dat_new_old1 = subset(dat, (repetition == 1) | (repetition == 2))
dat_new_old1$repetition = factor(dat_new_old1$repetition)
dat_new_old2 = subset(dat, (repetition == 1) | (repetition == 3))
dat_new_old2$repetition = factor(dat_new_old2$repetition)
dat_new_old3 = subset(dat, (repetition == 1) | (repetition == 3))
dat_new_old3$repetition = factor(dat_new_old3$repetition)
```

```{r estimatesepmodel, echo=T, results = 'hide', cache=T}
mod_pri = c(prior(normal(0,1), class=b),
            prior(cauchy(0,2), class=sigma))
mod_rep1 = brm(amplitude ~ repetition + (1 | subject), 
                      data = dat_new_old1, prior = mod_pri, save_all_pars = T)
mod_interact1 = brm(amplitude ~ repetition*ACP*LMR + (1 | subject),
                   data = dat_new_old1, prior = mod_pri, save_all_pars = T)
mod_rep2 = brm(amplitude ~ repetition + (1 | subject), 
                      data = dat_new_old2, prior = mod_pri, save_all_pars = T)
mod_interact2 = brm(amplitude ~ repetition*ACP*LMR + (1 | subject),
                   data = dat_new_old2, prior = mod_pri, save_all_pars = T)
mod_rep3 = brm(amplitude ~ repetition + (1 | subject), 
                      data = dat_new_old3, prior = mod_pri, save_all_pars = T)
mod_interact3 = brm(amplitude ~ repetition*ACP*LMR + (1 | subject),
                   data = dat_new_old3, prior = mod_pri, save_all_pars = T)
```

```{r calcBF_sep, echo=T, results = 'hide', cache=T}
#new_old1
bf1x = bayes_factor(mod_interact1, mod_rep1)$bf
#new old2
bf2x = bayes_factor(mod_interact2, mod_rep2)$bf
#new old3
bf3x = bayes_factor(mod_interact3, mod_rep3)$bf
```

```{r bf_sep, include = T, cache=T}
#new_old1
bf1x
waic(mod_interact1, mod_rep1)
#new_old2
bf2x
waic(mod_interact2, mod_rep2)
#new_old3
bf3x
waic(mod_interact3, mod_rep3)
```
