---
title: "model_building"
output: pdf_document
---

```{r setup, include=FALSE, cache = T}
knitr::opts_chunk$set(fig.width=12, fig.height=8, fig.path='Figs/',
                      echo=TRUE, warning=FALSE, message=FALSE)
```


```{r setup2, cache=T}
library(rio)
library(BayesFactor)
library(readxl)
library(reshape2)
library(ggplot2)
library(cowplot)
library(lme4)
library(lmerTest)
library(lsmeans)
theme2 = theme(panel.grid.major = element_blank(), 
               panel.grid.minor = element_blank(), 
               panel.background = element_blank(), 
               axis.line = element_line(colour = "black"), 
               legend.key = element_rect(fill = "white"),
               text = element_text(size = 17),
               #legend.position='none',
               plot.title = element_text(size = 20, face = 'plain'),
               axis.text.x= element_text(size=15),
               axis.text.y= element_text(size=15))
latency <- read_excel("S:/expt/eeg/eeg01/analyses/latency_old123.csv", 
                      col_names = FALSE)
colnames(latency) = c('Old1','Old2','Old3')
latency$subject = 1:nrow(latency)
longdat = melt(latency, id.vars = 'subject')
colnames(longdat) = c('Subject', 'Repetition','Latency')
```

### repetition latency

```{r replat, cache=T}
#overall
generalTestBF(Latency ~ Repetition, whichRandom = 'Subject', data = longdat)

#old1 vs old2
ttestBF(x = longdat$Latency[longdat$Repetition == 'Old1'],
        y = longdat$Latency[longdat$Repetition == 'Old2'])

#old1 vs old3
ttestBF(x = longdat$Latency[longdat$Repetition == 'Old1'],
        y = longdat$Latency[longdat$Repetition == 'Old3'])

#old2 vs old3
1/ttestBF(x = longdat$Latency[longdat$Repetition == 'Old2'],
          y = longdat$Latency[longdat$Repetition == 'Old3'])


#comparing with freq

#overall repetition
myfit = lmer(Latency ~ Repetition + (1|Subject),data = longdat)
anova(myfit)

lsmeans(myfit, pairwise ~ Repetition)


#means/sd
with(longdat, tapply(Latency, list(Repetition),mean,na.rm=T))
with(longdat, tapply(Latency, list(Repetition),sd,na.rm=T))

```


### repetition by short/long

```{r replatsl, cache=T}
latency_old123_shortlong = read_excel("S:/expt/eeg/eeg01/analyses/latency_old123_shortlong.csv", 
                                      col_names = FALSE)
colnames(latency_old123_shortlong) = c('o1S','o1L','o2S','o2L','o3S','o3L')
latency_old123_shortlong_long = melt(latency_old123_shortlong)
latency_old123_shortlong_long$repetition = c(rep('Old1',30),rep('Old2',30),rep('Old3',30))
latency_old123_shortlong_long$SL = c(rep(c(rep('S',15),rep('L',15)),3))

tmpo1 = subset(latency_old123_shortlong_long, repetition == 'Old1')
tmpo2 = subset(latency_old123_shortlong_long, repetition == 'Old2')
tmpo3 = subset(latency_old123_shortlong_long, repetition == 'Old3')

with(tmpo1, tapply(value, list(SL),mean,na.rm=T))*1000
with(tmpo1, tapply(value, list(SL),sd,na.rm=T))*1000

with(tmpo2, tapply(value, list(SL),mean,na.rm=T))*1000
with(tmpo2, tapply(value, list(SL),sd,na.rm=T))*1000

with(tmpo3, tapply(value, list(SL),mean,na.rm=T))*1000
with(tmpo3, tapply(value, list(SL),sd,na.rm=T))*1000

(bf1 = ttestBF(x = tmpo1$value[tmpo1$SL == 'S'],
               y = tmpo1$value[tmpo1$SL == 'L'],
               paired = T,
               nullInterval = c(0,-Inf)))

(bf2 = ttestBF(x = tmpo2$value[tmpo2$SL == 'S'],
               y = tmpo2$value[tmpo2$SL == 'L'],
               paired = T,
               nullInterval = c(0,-Inf)))

(bf3 = ttestBF(x = tmpo3$value[tmpo3$SL == 'S'],
               y = tmpo3$value[tmpo3$SL == 'L'],
               paired = T,
               nullInterval = c(0,-Inf)))
with(latency_old123_shortlong_long, tapply(value, list(repetition,SL),mean))


##frequentist
t.test(value ~ SL, paired = T, data = tmpo1, alternative = 'greater')
t.test(value ~ SL, paired = T, data = tmpo2, alternative = 'greater')
t.test(value ~ SL, paired = T, data = tmpo3, alternative = 'greater')

```

### ERP diffs latency graph
```{r erpdiffsl, cache=T}

lat_dat = import('S:/expt/eeg/eeg01/analyses/old123_by_shortlong.csv')
colnames(lat_dat) = c('o1s','o1l','o2s','o2l','o3s','o3l')
longlat = melt(lat_dat)
longlat$repetition = c(rep('Old 1',30), rep('Old 2',30),rep('Old 3',30))
longlat$SL = c(rep('Short',15),rep('Long',15),rep('Short',15),rep('Long',15),rep('Short',15),rep('Long',15))


erp_diff = read.csv('S:/expt/eeg/eeg01/analyses/leftpar_erp_diffs_old123_by_shortlong.csv',
                    header = F)
colnames(erp_diff) = seq(-495,1500,5)
erp_diff$subject = rep(seq(1,15,1),6)
erp_diff$repetition = c(rep('Old 1', 30),rep('Old 2',30),rep('Old 3',30))
erp_diff$SL = rep(c(rep('Short',15), rep('Long',15)),3)

long_erp_SL = melt(erp_diff, id.vars = c('subject','repetition','SL'))
colnames(long_erp_SL)
long_erp_SL$variable = as.numeric(as.character(long_erp_SL$variable))
long_erp_SL$SL = factor(long_erp_SL$SL)

o1_erp = subset(long_erp_SL, repetition == 'Old 1')
o2_erp = subset(long_erp_SL, repetition == 'Old 2')
o3_erp = subset(long_erp_SL, repetition == 'Old 3')



o1means = with(subset(longlat, repetition == 'Old 1'), tapply(value, list(SL),mean,na.rm=T))*1e3
o2means = with(subset(longlat, repetition == 'Old 2'), tapply(value, list(SL),mean,na.rm=T))*1e3
o3means = with(subset(longlat, repetition == 'Old 3'), tapply(value, list(SL),mean,na.rm=T))*1e3

omeans = with(longdat, tapply(Latency, list(Repetition),mean)) *1e3

windowsFonts(Times=windowsFont("Arial"))
platrep = ggplot(long_erp_SL, aes(variable, value)) + 
  theme2 +
  #stat_summary(fun.data = mean_cl_boot,geom = "ribbon",size = 1,aes(fill = repetition),alpha = 0.2)+
  guides(fill = "none")+
  stat_summary(fun.y = mean,geom = "line",size = 0.5,aes(colour = repetition))+
  labs(x = "Time (ms)",y = expression(paste("Amplitude (",mu,"V) Difference")),colour = "")+
  geom_vline(xintercept = 0,linetype = "dashed" )+
  geom_hline(yintercept = 0,linetype = "dashed")  +
  scale_fill_manual(values=c('red','darkgreen','blue')) +
  scale_color_manual(values=c('red','darkgreen','blue')) +
  theme(legend.position=c(0.7,0.8)) + 
  geom_segment(x=omeans[1],xend=omeans[1],y=0,
               yend=5.75, color = 'red', size = 0.5)+ 
  geom_segment(x=omeans[2],xend=omeans[2],y=0,
               yend=8.92, color = 'darkgreen', size = 0.5)+
  geom_segment(x=omeans[3],xend=omeans[3],y=0,
               yend=8.92, color = 'blue', size = 0.5)


#save_plot('C:/Users/jscof/OneDrive/Desktop/eeg01_latreppic.png',
#          base_height = 4,
#          base_aspect_ratio = 1.3,plot = platrep,type = 'cairo')

```

### LP Diff Repetition graph

```{r lpdiffrepg, cache=T}
theme2 = theme(panel.grid.major = element_blank(), 
               panel.grid.minor = element_blank(), 
               panel.background = element_blank(), 
               axis.line = element_line(colour = "black"), 
               legend.key = element_rect(fill = "white"),
               text = element_text(size = 17),
               #legend.position='none',
               plot.title = element_text(size = 20, face = 'plain'),
               axis.text.x= element_text(size=15),
               axis.text.y= element_text(size=15))

#### ERP diff graphs
erp_dat = import('S:/expt/eeg/eeg01/analyses/leftpar_erps_newold123.csv')
colnames(erp_dat) = seq(1,400,1)
erp_dat$subject = rep(seq(1,15,1),4)
erp_dat$repetition = c(rep('new',15),rep('o1',15), rep('o2',15),rep('o3',15))

big_long = data.frame()
subs = seq(1,15,1)
for(x in subs){
  tmpdat = subset(erp_dat, subject == x)
  tmpdat2 = data.frame(t(tmpdat[,c(1:400)]))
  colnames(tmpdat2) = c('zero','one','two','three')
  oned = tmpdat2$one - tmpdat2$zero
  twod = tmpdat2$two - tmpdat2$zero
  threed = tmpdat2$three - tmpdat2$zero
  tmpdf = data.frame(cbind(oned,twod,threed))
  colnames(tmpdf) = c('Old 1', 'Old 2', 'Old 3')
  longtmp = melt(tmpdf)
  longtmp$subject = x
  longtmp$time = seq(-495,1500,5)
  big_long = rbind(big_long, longtmp)
}

## Plot ERP
windowsFonts(Times=windowsFont("Arial"))
erp_w_ribbon = ggplot(big_long, aes(time, value)) + theme2 +
  stat_summary(fun.data = mean_cl_boot,geom = "ribbon",size = 1,aes(fill = variable),alpha = 0.3)+
  guides(fill = "none")+
  stat_summary(fun.y = mean,geom = "line",size = 0.55,aes(colour = variable))+
  scale_color_manual(values=c('red','darkgreen','blue'))+
  labs(x = "Time (ms)",y = expression(paste("Amplitude (",mu,"V) Difference")),colour = "")+
  geom_vline(xintercept = 0,linetype = "dashed" )+
  geom_hline(yintercept = 0,linetype = "dashed") +
  theme(legend.position=c(0.4,0.2))



#save_plot('C:/Users/jscof/OneDrive/Desktop/eeg01_LPE_diff_w_ribbon.png',
#          base_height = 4,
#          base_aspect_ratio = 1.3,plot = erp_w_ribbon,type = 'cairo')
```

### ERP repetition latency by Short/Long

```{r erpreplatbysl, cache=T}
erp_diff = read.csv('S:/expt/eeg/eeg01/analyses/leftpar_erp_diffs_old123_by_shortlong.csv',
                    header = F)
colnames(erp_diff) = seq(-495,1500,5)
erp_diff$subject = rep(seq(1,15,1),6)
erp_diff$repetition = c(rep('Old 1', 30),rep('Old 2',30),rep('Old 3',30))
erp_diff$SL = rep(c(rep('Short',15), rep('Long',15)),3)

long_erp_SL = melt(erp_diff, id.vars = c('subject','repetition','SL'))
colnames(long_erp_SL)
long_erp_SL$variable = as.numeric(as.character(long_erp_SL$variable))
long_erp_SL$SL = factor(long_erp_SL$SL)

o1_erp = subset(long_erp_SL, repetition == 'Old 1')
o2_erp = subset(long_erp_SL, repetition == 'Old 2')
o3_erp = subset(long_erp_SL, repetition == 'Old 3')

o1means = with(subset(longlat, repetition == 'Old 1'), tapply(value, list(SL),mean,na.rm=T))*1e3
o2means = with(subset(longlat, repetition == 'Old 2'), tapply(value, list(SL),mean,na.rm=T))*1e3
o3means = with(subset(longlat, repetition == 'Old 3'), tapply(value, list(SL),mean,na.rm=T))*1e3

theme2 = theme(panel.grid.major = element_blank(), 
               panel.grid.minor = element_blank(), 
               panel.background = element_blank(), 
               axis.line = element_line(colour = "black"), 
               legend.key = element_rect(fill = "white"),
               text = element_text(size = 30),
               #legend.position='none',
               plot.title = element_text(size = 30, face = 'plain'),
               axis.text.x= element_text(size=28),
               axis.text.y= element_text(size=28))
## Old 1
o1_SL_lat = ggplot(o1_erp, aes(variable, value)) + 
  theme2 +labs(title='Old 1') + theme(plot.title = element_text(hjust = 0.5)) + 
  #stat_summary(fun.data = mean_cl_boot,geom = "ribbon",size = 1,aes(fill = SL),alpha = 0.2)+
  guides(fill = "none")+
  stat_summary(fun.y = mean,geom = "line",size = 1,aes(colour = SL))+
  labs(x = "",y = NULL)+
  geom_vline(xintercept = 0,linetype = "dashed" )+
  geom_hline(yintercept = 0,linetype = "dashed")  +
  scale_fill_manual(values=c('firebrick3','dodgerblue4')) +
  scale_color_manual(values=c('firebrick3','dodgerblue4')) +
  coord_cartesian(ylim=c(-5,10)) + 
  geom_segment(x=o1means[1],xend=o1means[1],y=0,
               yend=5.04, color = 'firebrick3', size = 1) +
  geom_segment(x=o1means[2],xend=o1means[2],y=0,
               yend=7.2, color = 'dodgerblue4', size = 1) +
  theme(legend.position=c(0.7,0.8))
## Old 2
o2_SL_lat = ggplot(o2_erp, aes(variable, value)) + 
  theme2 +labs(title='Old 2') + theme(plot.title = element_text(hjust = 0.5)) + 
  #stat_summary(fun.data = mean_cl_boot,geom = "ribbon",size = 1,aes(fill = SL),alpha = 0.2)+
  guides(fill = "none")+
  stat_summary(fun.y = mean,geom = "line",size = 1,aes(colour = SL))+
  labs(x = "",y = NULL)+
  geom_vline(xintercept = 0,linetype = "dashed" )+
  geom_hline(yintercept = 0,linetype = "dashed")  +
  scale_fill_manual(values=c('firebrick3','dodgerblue4')) +
  scale_color_manual(values=c('firebrick3','dodgerblue4')) +
  coord_cartesian(ylim=c(-5,10)) + 
  geom_segment(x=o2means[1],xend=o2means[1],y=0,
               yend=8.9, color = 'firebrick3', size = 1) +
  geom_segment(x=o2means[2],xend=o2means[2],y=0,
               yend=9.4, color = 'dodgerblue4', size = 1) +
  theme(legend.position='none')
## Old 3
o3_SL_lat = ggplot(o3_erp, aes(variable, value)) + 
  theme2 +labs(title='Old 3') + theme(plot.title = element_text(hjust = 0.5)) + 
  #stat_summary(fun.data = mean_cl_boot,geom = "ribbon",size = 1,aes(fill = SL),alpha = 0.2)+
  guides(fill = "none")+
  stat_summary(fun.y = mean,geom = "line",size = 1,aes(colour = SL))+
  labs(x = "Time (ms)",y = NULL)+
  geom_vline(xintercept = 0,linetype = "dashed" )+
  geom_hline(yintercept = 0,linetype = "dashed")  +
  scale_fill_manual(values=c('firebrick3','dodgerblue4')) +
  scale_color_manual(values=c('firebrick3','dodgerblue4')) +
  coord_cartesian(ylim=c(-5,10)) + 
  geom_segment(x=o3means[1],xend=o3means[1],y=0,
               yend=8.4, color = 'firebrick3', size = 1) +
  geom_segment(x=o3means[2],xend=o3means[2],y=0,
               yend=9.78, color = 'dodgerblue4', size = 1) +
  theme(legend.position='none')



#plot with ribbons
erp_SL_diff_pic = plot_grid(o1_SL_lat, o2_SL_lat, o3_SL_lat, ncol = 1, 
           scale = 0.9)

#save_plot('C:/Users/jscof/OneDrive/Desktop/latency_by_SL_rep.png', base_height = 5,
#          base_aspect_ratio = 2.3,plot = erp_SL_diff_pic,type = 'cairo', ncol=1,nrow=3)

```
